name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      #- name: Set env
      #  run:  export CGO_ENABLED=0 & export GOOS=linux
      #- name: Go the project
      #  run: | 
      #    go mod download

      - name: Build the project
        run: | 
          CGO_ENABLED=0 go build -o ./local_trableshoot -ldflags="-X 'local_trableshoot/configs.Version=0.3.6'" ./cmd/app

      - name: Archive build
        run: tar -czvf local_trableshoot.tar.gz ./local_trableshoot

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./local_trableshoot.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}