name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Срабатывает на теги, начинающиеся с "v" (например, v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # Замените на нужную версию Go

      - name: Build the project
        run: go build -o ./local_trableshoot ./cmd/app

      - name: Archive build
        run: tar -czvf local_trableshoot.tar.gz ./local_trableshoot

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./local_trableshoot.tar.gz
          asset_name: local_trableshoot.tar.gz
          asset_content_type: application/gzip